Repository asdf-community/asdf-plugin-manager, pull requests merged in 2023-09, with the labels that each got.

#14 refactor: add flag to remove plugin if it's already installed
  cli/asdf-plugin-manager.sh
Labels: enhancement

#15 feat: add update and update-all options
  README.md
  cli/asdf-plugin-manager.sh
Labels: enhancement

#17 fix: ensure 2nd arg is provided for the options need it
  cli/asdf-plugin-manager.sh
Labels: bug

#19 fix: use syntax compatible with bash 3
  .github/workflows/build.yml
  cli/asdf-plugin-manager.sh
Labels: bug

#26 docs: use v1.1.1 in the readme
  README.md
Labels: documentation
